### ISSUE TITLE
Externalize the notes

### ISSUE THREAD

**Issue by kferrone** [PyvesB/Notepad4e#3]
As a note taker I would like to have my notes externalized so that I can use my notes across numerous workspaces. 

The same feature is available in the Mylyn plugin which asks where your task repo is. Basically I go to .metadata folder and grab the .mylyn folder and copy/cut then paste to where I want it. In the preferences page for Mylyn I tell it where my mylyn tasks are. Notepad4e should do the same. 

My main issue is sometimes I totally wreck a workspace and I need to rebuild it and I don't want to lose my notes or have to hunt them down in the .metadata and copy over to new workspace. 

Also If I simply want the same notes in another workspace I have to copy/paste them to and from each workspace to keep them synced.

**Comment by PyvesB** [comment]
Hello @kferrone!

I'm quite busy at the moment, but I'll consider this request for a future update! 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
@kferrone I have implemented and released this feature in Notepad4e version 1.5.0. You can now override the default location in the plugin's preferences. Let me know what you think!

**Comment by PyvesB** [comment]
@kferrone you're welcome! Feel free to star the repository and the listing on the Eclipse Marketplace, it will help the plugin get a bit more visibility. 😉
