### ISSUE TITLE
Formatting cant be undone

### ISSUE THREAD

**Issue by Klaboe** [PyvesB/Notepad4e#5]
If you apply some formatting, you cant undo it when pressing the formatting button again.

You need to copy/paste it and depend on the other issue here about formatting 😅

**Comment by Klaboe** [comment]
I now see the clear formatting button. Nvm

**Comment by PyvesB** [comment]
Hey there 👋🏻 

Indeed, there's a Clear Style button to get rid of formatting on a section of text. You can also toggle it via its shortcut, Ctrl + D, or Cmd + D on macOS. 😉
